#############################################################################
# Makefile for building: TaskManager
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  TaskManager.pro
# Template: app
# Command: /home/ramon/Qt/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile TaskManager.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I/home/ramon/Qt/5.4/gcc_64/include -I/home/ramon/Qt/5.4/gcc_64/include/QtWidgets -I/home/ramon/Qt/5.4/gcc_64/include/QtGui -I/home/ramon/Qt/5.4/gcc_64/include/QtCore -I. -I. -I/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ramon/Qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TaskManager1.0.0
DISTDIR = /home/ramon/BTI/Códigos/2015.1/ISO/Trabalhos/trabalhoTaskManager/BTI_TaskManager-master\ (3)/.tmp/TaskManager1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ramon/Qt/5.4/gcc_64 -Wl,-rpath,/home/ramon/Qt/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/ramon/Qt/5.4/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		thread.cpp \
		processeslist.cpp \
		tabone.cpp \
		semaforo.cpp \
		InfoSO.cpp \
		tabthree.cpp \
		NameComputer.cpp \
		cpuinfo.cpp moc_mainwindow.cpp \
		moc_tabone.cpp \
		moc_tabthree.cpp
OBJECTS       = main.o \
		mainwindow.o \
		thread.o \
		processeslist.o \
		tabone.o \
		semaforo.o \
		InfoSO.o \
		tabthree.o \
		NameComputer.o \
		cpuinfo.o \
		moc_mainwindow.o \
		moc_tabone.o \
		moc_tabthree.o
DIST          = /home/ramon/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/resources.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/moc.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/uic.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		TaskManager.pro mainwindow.h \
		thread.h \
		processeslist.h \
		tabone.h \
		semaforo.h \
		InfoSO.h \
		tabthree.h \
		NameComputer.h \
		cpuinfo.h main.cpp \
		mainwindow.cpp \
		thread.cpp \
		processeslist.cpp \
		tabone.cpp \
		semaforo.cpp \
		InfoSO.cpp \
		tabthree.cpp \
		NameComputer.cpp \
		cpuinfo.cpp
QMAKE_TARGET  = TaskManager
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = TaskManager


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TaskManager.pro /home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf /home/ramon/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/resources.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/moc.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/uic.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		/home/ramon/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		TaskManager.pro \
		/home/ramon/Qt/5.4/gcc_64/lib/libQt5Widgets.prl \
		/home/ramon/Qt/5.4/gcc_64/lib/libQt5Gui.prl \
		/home/ramon/Qt/5.4/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile TaskManager.pro
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/unix.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/linux.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/qconfig.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/default_post.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/qt.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/resources.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/moc.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/uic.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/unix/thread.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/yacc.prf:
/home/ramon/Qt/5.4/gcc_64/mkspecs/features/lex.prf:
TaskManager.pro:
/home/ramon/Qt/5.4/gcc_64/lib/libQt5Widgets.prl:
/home/ramon/Qt/5.4/gcc_64/lib/libQt5Gui.prl:
/home/ramon/Qt/5.4/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile TaskManager.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h thread.h processeslist.h tabone.h semaforo.h InfoSO.h tabthree.h NameComputer.h cpuinfo.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp thread.cpp processeslist.cpp tabone.cpp semaforo.cpp InfoSO.cpp tabthree.cpp NameComputer.cpp cpuinfo.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_tabone.cpp moc_tabthree.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_tabone.cpp moc_tabthree.cpp
moc_mainwindow.cpp: /home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QMainWindow \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpalette.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qline.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcursor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qurl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qicon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/QStandardItem \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QSplitter \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qsplitter.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qframe.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QTimer \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtimer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QList \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		tabone.h \
		thread.h \
		processeslist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject \
		mainwindow.h
	/home/ramon/Qt/5.4/gcc_64/bin/moc $(DEFINES) -I/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++ -I'/home/ramon/BTI/Códigos/2015.1/ISO/Trabalhos/trabalhoTaskManager/BTI_TaskManager-master (3)' -I/home/ramon/Qt/5.4/gcc_64/include -I/home/ramon/Qt/5.4/gcc_64/include/QtWidgets -I/home/ramon/Qt/5.4/gcc_64/include/QtGui -I/home/ramon/Qt/5.4/gcc_64/include/QtCore mainwindow.h -o moc_mainwindow.cpp

moc_tabone.cpp: thread.h \
		processeslist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/QStandardItem \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qline.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qicon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QList \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject \
		tabone.h
	/home/ramon/Qt/5.4/gcc_64/bin/moc $(DEFINES) -I/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++ -I'/home/ramon/BTI/Códigos/2015.1/ISO/Trabalhos/trabalhoTaskManager/BTI_TaskManager-master (3)' -I/home/ramon/Qt/5.4/gcc_64/include -I/home/ramon/Qt/5.4/gcc_64/include/QtWidgets -I/home/ramon/Qt/5.4/gcc_64/include/QtGui -I/home/ramon/Qt/5.4/gcc_64/include/QtCore tabone.h -o moc_tabone.cpp

moc_tabthree.cpp: thread.h \
		InfoSO.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		NameComputer.h \
		cpuinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject \
		tabthree.h
	/home/ramon/Qt/5.4/gcc_64/bin/moc $(DEFINES) -I/home/ramon/Qt/5.4/gcc_64/mkspecs/linux-g++ -I'/home/ramon/BTI/Códigos/2015.1/ISO/Trabalhos/trabalhoTaskManager/BTI_TaskManager-master (3)' -I/home/ramon/Qt/5.4/gcc_64/include -I/home/ramon/Qt/5.4/gcc_64/include/QtWidgets -I/home/ramon/Qt/5.4/gcc_64/include/QtGui -I/home/ramon/Qt/5.4/gcc_64/include/QtCore tabthree.h -o moc_tabthree.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/ramon/Qt/5.4/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp /home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QApplication \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qapplication.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qeventloop.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcursor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpalette.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qline.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qurl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qguiapplication.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qinputmethod.h \
		mainwindow.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QMainWindow \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qicon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/QStandardItem \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QSplitter \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qsplitter.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qframe.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QTimer \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtimer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QList \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		tabone.h \
		thread.h \
		processeslist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QMainWindow \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpalette.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qline.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcursor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qurl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qicon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/QStandardItem \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QSplitter \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qsplitter.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qframe.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QTimer \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtimer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QList \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		tabone.h \
		thread.h \
		processeslist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject \
		ui_mainwindow.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QVariant \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QAction \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qaction.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QApplication \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qapplication.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qeventloop.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qguiapplication.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qinputmethod.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QButtonGroup \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qbuttongroup.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QDial \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qdial.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QGroupBox \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qgroupbox.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QHeaderView \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qheaderview.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qvalidator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregularexpression.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qslider.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qstyle.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QLCDNumber \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qlcdnumber.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QLabel \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QLineEdit \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qlineedit.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtextcursor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtextformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpen.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtextoption.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QMenuBar \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qmenubar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qmenu.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QProgressBar \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qprogressbar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QPushButton \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QStatusBar \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QTabWidget \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QTableView \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qtableview.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QToolBar \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/qtoolbar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtWidgets/QWidget \
		tabthree.h \
		InfoSO.h \
		NameComputer.h \
		cpuinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

thread.o: thread.cpp thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

processeslist.o: processeslist.cpp processeslist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/QStandardItem \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qline.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qicon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QList \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processeslist.o processeslist.cpp

tabone.o: tabone.cpp tabone.h \
		thread.h \
		processeslist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/QStandardItem \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qstandarditemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qline.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtGui/qicon.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QList \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabone.o tabone.cpp

semaforo.o: semaforo.cpp semaforo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o semaforo.o semaforo.cpp

InfoSO.o: InfoSO.cpp InfoSO.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDir \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InfoSO.o InfoSO.cpp

tabthree.o: tabthree.cpp tabthree.h \
		thread.h \
		InfoSO.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		NameComputer.h \
		cpuinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabthree.o tabthree.cpp

NameComputer.o: NameComputer.cpp NameComputer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDir \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NameComputer.o NameComputer.cpp

cpuinfo.o: cpuinfo.cpp cpuinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QString \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDir \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdir.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/QDebug \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qset.h \
		/home/ramon/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cpuinfo.o cpuinfo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tabone.o: moc_tabone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabone.o moc_tabone.cpp

moc_tabthree.o: moc_tabthree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabthree.o moc_tabthree.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

